/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as DevAtomsRouteImport } from './routes/_dev/atoms'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppPodsIndexRouteImport } from './routes/_app/pods/index'
import { Route as AppPodsPodIdRouteRouteImport } from './routes/_app/pods/$podId/route'
import { Route as AppPodsPodIdIndexRouteImport } from './routes/_app/pods/$podId/index'
import { Route as AppPodsPodIdSettingsRouteImport } from './routes/_app/pods/$podId/settings'
import { Route as AppPodsPodIdMembersRouteImport } from './routes/_app/pods/$podId/members'
import { Route as AppPodsPodIdInvitesRouteImport } from './routes/_app/pods/$podId/invites'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DevAtomsRoute = DevAtomsRouteImport.update({
  id: '/_dev/atoms',
  path: '/atoms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppPodsIndexRoute = AppPodsIndexRouteImport.update({
  id: '/pods/',
  path: '/pods/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPodsPodIdRouteRoute = AppPodsPodIdRouteRouteImport.update({
  id: '/pods/$podId',
  path: '/pods/$podId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPodsPodIdIndexRoute = AppPodsPodIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPodsPodIdRouteRoute,
} as any)
const AppPodsPodIdSettingsRoute = AppPodsPodIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppPodsPodIdRouteRoute,
} as any)
const AppPodsPodIdMembersRoute = AppPodsPodIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppPodsPodIdRouteRoute,
} as any)
const AppPodsPodIdInvitesRoute = AppPodsPodIdInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => AppPodsPodIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/atoms': typeof DevAtomsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/invite/$token': typeof InviteTokenRoute
  '/pods/$podId': typeof AppPodsPodIdRouteRouteWithChildren
  '/pods/': typeof AppPodsIndexRoute
  '/pods/$podId/invites': typeof AppPodsPodIdInvitesRoute
  '/pods/$podId/members': typeof AppPodsPodIdMembersRoute
  '/pods/$podId/settings': typeof AppPodsPodIdSettingsRoute
  '/pods/$podId/': typeof AppPodsPodIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/atoms': typeof DevAtomsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/invite/$token': typeof InviteTokenRoute
  '/pods': typeof AppPodsIndexRoute
  '/pods/$podId/invites': typeof AppPodsPodIdInvitesRoute
  '/pods/$podId/members': typeof AppPodsPodIdMembersRoute
  '/pods/$podId/settings': typeof AppPodsPodIdSettingsRoute
  '/pods/$podId': typeof AppPodsPodIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_dev/atoms': typeof DevAtomsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/pods/$podId': typeof AppPodsPodIdRouteRouteWithChildren
  '/_app/pods/': typeof AppPodsIndexRoute
  '/_app/pods/$podId/invites': typeof AppPodsPodIdInvitesRoute
  '/_app/pods/$podId/members': typeof AppPodsPodIdMembersRoute
  '/_app/pods/$podId/settings': typeof AppPodsPodIdSettingsRoute
  '/_app/pods/$podId/': typeof AppPodsPodIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/atoms'
    | '/auth/callback'
    | '/invite/$token'
    | '/pods/$podId'
    | '/pods/'
    | '/pods/$podId/invites'
    | '/pods/$podId/members'
    | '/pods/$podId/settings'
    | '/pods/$podId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/atoms'
    | '/auth/callback'
    | '/invite/$token'
    | '/pods'
    | '/pods/$podId/invites'
    | '/pods/$podId/members'
    | '/pods/$podId/settings'
    | '/pods/$podId'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_auth/login'
    | '/_auth/register'
    | '/_dev/atoms'
    | '/auth/callback'
    | '/invite/$token'
    | '/_app/'
    | '/_app/pods/$podId'
    | '/_app/pods/'
    | '/_app/pods/$podId/invites'
    | '/_app/pods/$podId/members'
    | '/_app/pods/$podId/settings'
    | '/_app/pods/$podId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DevAtomsRoute: typeof DevAtomsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dev/atoms': {
      id: '/_dev/atoms'
      path: '/atoms'
      fullPath: '/atoms'
      preLoaderRoute: typeof DevAtomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/pods/': {
      id: '/_app/pods/'
      path: '/pods'
      fullPath: '/pods/'
      preLoaderRoute: typeof AppPodsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/pods/$podId': {
      id: '/_app/pods/$podId'
      path: '/pods/$podId'
      fullPath: '/pods/$podId'
      preLoaderRoute: typeof AppPodsPodIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/pods/$podId/': {
      id: '/_app/pods/$podId/'
      path: '/'
      fullPath: '/pods/$podId/'
      preLoaderRoute: typeof AppPodsPodIdIndexRouteImport
      parentRoute: typeof AppPodsPodIdRouteRoute
    }
    '/_app/pods/$podId/settings': {
      id: '/_app/pods/$podId/settings'
      path: '/settings'
      fullPath: '/pods/$podId/settings'
      preLoaderRoute: typeof AppPodsPodIdSettingsRouteImport
      parentRoute: typeof AppPodsPodIdRouteRoute
    }
    '/_app/pods/$podId/members': {
      id: '/_app/pods/$podId/members'
      path: '/members'
      fullPath: '/pods/$podId/members'
      preLoaderRoute: typeof AppPodsPodIdMembersRouteImport
      parentRoute: typeof AppPodsPodIdRouteRoute
    }
    '/_app/pods/$podId/invites': {
      id: '/_app/pods/$podId/invites'
      path: '/invites'
      fullPath: '/pods/$podId/invites'
      preLoaderRoute: typeof AppPodsPodIdInvitesRouteImport
      parentRoute: typeof AppPodsPodIdRouteRoute
    }
  }
}

interface AppPodsPodIdRouteRouteChildren {
  AppPodsPodIdInvitesRoute: typeof AppPodsPodIdInvitesRoute
  AppPodsPodIdMembersRoute: typeof AppPodsPodIdMembersRoute
  AppPodsPodIdSettingsRoute: typeof AppPodsPodIdSettingsRoute
  AppPodsPodIdIndexRoute: typeof AppPodsPodIdIndexRoute
}

const AppPodsPodIdRouteRouteChildren: AppPodsPodIdRouteRouteChildren = {
  AppPodsPodIdInvitesRoute: AppPodsPodIdInvitesRoute,
  AppPodsPodIdMembersRoute: AppPodsPodIdMembersRoute,
  AppPodsPodIdSettingsRoute: AppPodsPodIdSettingsRoute,
  AppPodsPodIdIndexRoute: AppPodsPodIdIndexRoute,
}

const AppPodsPodIdRouteRouteWithChildren =
  AppPodsPodIdRouteRoute._addFileChildren(AppPodsPodIdRouteRouteChildren)

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppPodsPodIdRouteRoute: typeof AppPodsPodIdRouteRouteWithChildren
  AppPodsIndexRoute: typeof AppPodsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppPodsPodIdRouteRoute: AppPodsPodIdRouteRouteWithChildren,
  AppPodsIndexRoute: AppPodsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DevAtomsRoute: DevAtomsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
